language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

after_success:
  - ./gradlew jacocoRootReport coveralls
  - cp -r build/reports/jacoco/jacocoRootReport build/reports/jacoco/jacocoTestReport
  - ./gradlew coveralls
